### ISSUE TITLE
Details in the migrate from cra guide

### ISSUE THREAD

**Issue by giankotarola** [web-infra-dev/rspack-website#219]
Hey! Just want to share some details that found on https://github.com/web-infra-dev/rspack-website/blob/main/docs/en/guide/migrate-from-cra.mdx#configure-rspackconfigjs section when trying to following it.

Found some extra spaces in these values:
- https://github.com/web-infra-dev/rspack-website/blob/main/docs/en/guide/migrate-from-cra.mdx?plain=1#L37
- https://github.com/web-infra-dev/rspack-website/blob/main/docs/en/guide/migrate-from-cra.mdx?plain=1#L42

#### **Update: rspack only support copy-webpack-plugin@5**
~And the arg that is passed to the new CopyPlugin constructor, https://github.com/web-infra-dev/rspack-website/blob/main/docs/en/guide/migrate-from-cra.mdx?plain=1#L47, is different from what it is mentioned in https://webpack.js.org/plugins/copy-webpack-plugin/#options doc.~

~As a side note, when doing the changes for the plugin, i'm not able to run/build the project as it throws the next error:~
```sh
> rspack-react-starter@0.0.0 build
> rspack build

[rspack-cli] [Error: napi error: GenericFailure - TypeError: compilation.getCache is not a function
    at /Users/***/Documents/projects/rspack-project/node_modules/copy-webpack-plugin/dist/index.js:693:33
    at Hook.eval (eval at create (/Users/***/Documents/projects/rspack-project/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/***/Documents/projects/rspack-project/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler._Compiler_newCompilation (/Users/***/Documents/projects/rspack-project/node_modules/@rspack/core/src/compiler.ts:358:30)
   0: _napi_register_module_v1
   1: <unknown>
   2: <unknown>
] {
  code: 'GenericFailure'
}
```

~Tested too by creating a new app with `npm create rspack@latest` and get the same error when using the copy webpack plugin.~

Btw, thank you for this great project!

**Comment by giankotarola** [comment]
I just opened https://github.com/web-infra-dev/rspack-website/pull/220 for updating the migrate from cra guide with the details mentioned
